// This is an autogenerated header file
#ifndef JL_VERSION_H
#define JL_VERSION_H
#define JULIA_VERSION_STRING "1.11.2"
#define JULIA_VERSION_MAJOR 1
#define JULIA_VERSION_MINOR 11
#define JULIA_VERSION_PATCH 2
#define JULIA_VERSION_IS_RELEASE 1
#endif
